# Site settings
title: The Cat Blog
header-img: img/home-bg.jpg
email: raymondcamden@gmail.com
copyright_name: Your/Project/Corporate Name
description: "A blog about cats!"
url: "http://yourdomain.com"
twitter_username: SBootstrap
email_username:  raymondcamden@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
